### ISSUE TITLE
Number of audioframes processed discrepancy on first and last tracks

### ISSUE THREAD

**Issue by ItchyData** [EuFlo/sacd-ripper#5]
I've converted a number of SACDs from ISO to DSF files using `sacd_extract`. The command I am using on macOS big sur 11.2.1 is

`sacd_extract -2 -s -c -A -i Willy.And.The.Poorboys.SACD.ISO/Willy\ And\ The\ Poorboys.iso  -y ~/Downloads/Music`

In each conversion there is one more audioframe processed than specified in the first track and one less then specified in the last track. It's happened for each conversion that I've done, so its probably not a coincidence. Here is a typical output: **note the discrepancy in the first track and last track**. 

Is this anything to be concerned with? Normal behavior? A bug? I haven't noticed any issues with the audio during playback for either the first or last track so all seems well quality wise. Thanks for the help! 

EDIT: I noticed that I only get this issue for SACD's not compressed with DST. If the SACD uses DST compression I don't get this warning. 

```
sacd_extract client 0.3.9.3-93-gbd0a00d35a01f9556a406c6c113dc31a84af2544

Enhanced by euflo ....starting!

Current (working) directory (for the app and 'sacd_extract.cfg' file): /Users/Itchydata

 Exporting DSF output in folder: /Creedence Clearwater Revival - Willy And The Poorboys

 Started at: Sun Feb 14 09:01:04 2021
    

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/01 - Down On The Corner.dsf] (1/10)..
Completed: 100% (file sectors processed: 58315 / total sectors:58315), Total: 7% (total sectors processed: 58315 / total sectors: 734165)
 
 Processed 12349 audioframes. Duration specified: 12348 (02:44:48 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/02 - It Came Out Of The Sky.dsf] (2/10)..
Completed: 100% (file sectors processed: 62073 / total sectors:62073), Total: 16% (total sectors processed: 120388 / total sectors: 734165)
 
 Processed 13301 audioframes. Duration specified: 13301 (02:57:26 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/03 - Cotton Fields.dsf] (3/10)..
Completed: 100% (file sectors processed: 61073 / total sectors:61073), Total: 24% (total sectors processed: 181461 / total sectors: 734165)
 
 Processed 13087 audioframes. Duration specified: 13087 (02:54:37 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/04 - Poorboy Shuffle.dsf] (4/10)..
Completed: 100% (file sectors processed: 48241 / total sectors:48241), Total: 31% (total sectors processed: 229702 / total sectors: 734165)
 
 Processed 10337 audioframes. Duration specified: 10337 (02:17:62 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/05 - Feelin' Blue.dsf] (5/10)..
Completed: 100% (file sectors processed: 110750 / total sectors:110750), Total: 46% (total sectors processed: 340452 / total sectors: 734165)
 
 Processed 23732 audioframes. Duration specified: 23732 (05:16:32 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/06 - Fortunate Son.dsf] (6/10)..
Completed: 100% (file sectors processed: 49556 / total sectors:49556), Total: 53% (total sectors processed: 390008 / total sectors: 734165)
 
 Processed 10619 audioframes. Duration specified: 10619 (02:21:44 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/07 - Don't Look Now (It Ain't You Or Me).dsf] (7/10)..
Completed: 100% (file sectors processed: 46113 / total sectors:46113), Total: 59% (total sectors processed: 436121 / total sectors: 734165)
 
 Processed 9881 audioframes. Duration specified: 9881 (02:11:56 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/08 - The Midnight Special.dsf] (8/10)..
Completed: 100% (file sectors processed: 89064 / total sectors:89064), Total: 71% (total sectors processed: 525185 / total sectors: 734165)
 
 Processed 19085 audioframes. Duration specified: 19085 (04:14:35 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/09 - Side O' The Road.dsf] (9/10)..
Completed: 100% (file sectors processed: 71891 / total sectors:71891), Total: 81% (total sectors processed: 597076 / total sectors: 734165)
 
 Processed 15405 audioframes. Duration specified: 15405 (03:25:30 [mins:secs:frames])

Processing [/Creedence Clearwater Revival - Willy And The Poorboys/10 - Effigy.dsf] (10/10)..
Completed: 100% (file sectors processed: 137089 / total sectors:137089), Total: 100% (total sectors processed: 734165 / total sectors: 734165)
 
 Warning: Number of processed audioframes (29375) is smaller than number of frames in duration (29376) 

 
 Processed 29375 audioframes. Duration specified: 29376 (06:31:51 [mins:secs:frames])


 Ended at: Sun Feb 14 09:01:07 2021
 [elapsed: 00 hours:00 minutes:03 seconds]


 We are done exporting DSF..                                                          

Program terminates!
```

**Comment by EuFlo** [comment]
I am aware of this problem. Till now, I did not found a reasonable cause.
A missing audioframe must not be a concern (the length of audioframe is 1/75 of second).
The app makes a comparative between real audioframes processed and the number of audioframes embedded in each  metadata's tracks.

**Comment by EuFlo** [comment]
Try to change 'pauses=1' in config file. Then re-run the app. This will include all the pauses.

**Comment by ItchyData** [comment]
I can confirm that using the `-b` flag does get rid of the error messages. But then I'm getting output that has a lot of audioframes that are not part of the original (this is the pauses of course):

` Processed 26475 audioframes. Duration specified: 26325 (05:51:00 [mins:secs:frames])`

And yet still other tracks have the exact number of frames with and without pauses. 

How does adding pauses affect gapless playback? Should tracks that are meant to be gapless still be so even when including pauses? 

Any general best practices for including the pauses or not? I assume that since the default is the exclude them, that should be the best practice? 

Thanks for the information.

**Comment by EuFlo** [comment]
The best practice is to remove pauses.

In a few days I will push a new build that fix this bug.

**Comment by ItchyData** [comment]
> The best practice is to remove pauses.
> 
> In a few days I will push a new build that fix this bug.

Ok, will keep pauses removed going forward. Thanks for pushing the bug fix. I'll hold off on my extractions until the new build is released. Best regards.

**Comment by EuFlo** [comment]
Uploaded new build sacd_extract.0.3.9.3-99 which fix the bug.

**Comment by ItchyData** [comment]
I've done about 10 extracts from my ISOs and no issues at all. Thanks for pushing the fix.
