### ISSUE TITLE
Long option '--select-track' broken?

### ISSUE THREAD

**Issue by MCKitch** [EuFlo/sacd-ripper#7]
Hi,

sacd_extract reports the following when the long option '--select-track' is used.

sacd_extract.exe --input 192.168.1.84:2002 --2ch-tracks --output-dsf --select-track 1,2,3,4 --output-dir C:\Users\micha\Music\SACD-Rips
sacd_extract.exe: unrecognized option `--select-track'
Usage: sacd_extract.exe [options] -i[=FILE]
Options:
...

Notes:
1. Tried both '99' and '107' versions
2. '-t' short option (of course) works ;-)

Cheers,
Mike

**Comment by EuFlo** [comment]
Hi,
Yep, it did not exist in the original/master version too.

**Comment by EuFlo** [comment]
I will fix it in the next update.
Thank you!

**Comment by MCKitch** [comment]
Cheers! :-)

**Comment by EuFlo** [comment]
Fixed now.

**Comment by MCKitch** [comment]
Thanks.  I'll try it out on my next rip. 😉
